config/routes.rb
Bcn::Application.routes.draw do  
  match "trabajo_parlamentario/index" => "trabajo_parlamentario#index", :as => :trabajo_parlamentario
  match "trabajo_parlamentario/create" => "trabajo_parlamentario#create", :via => :post, :as => :create_trabajo_parlamentario

  resources :bitacoras
  resources :tramite_normativos
  resources :tramite_constitucionals
  resources :debate_types
  resources :tp_generated_params
  resources :taxonomy_terms
  resources :taxonomy_categories
  resources :tp_parameters
  resources :default_users_by_ot_types
  resources :am_module_configurations
  resources :poblamiento_generated_params
  resources :poblamiento_import_locations
  resources :poblamiento_file_formats
  resources :doc_type_am_configurations
  resources :task_transitions
  resources :poblamiento_params
  resources :observation_types
  resources :target_document_versions
  resources :markup_tools
  resources :am_configurations
  resources :am_observations
  resources :am_run_observation_types
  resources :am_results
  resources :intermediaries
  resources :delivery_methods
  resources :observations
  resources :ot_states
  resources :audits
  resources :frbr_manifestations
  resources :frbr_expressions
  resources :frbr_document_types
  resources :frbr_works
  resources :frbr_bcn_types
  resources :frbr_entities
  resources :task_types
  resources :roles
  resources :priorities
  resources :ot_types
  resources :ots
  resources :tasks
  devise_for :users

  match "parlamentarians" => 'parlamentarians#create', :via => :post
  match "parlamentarians" => 'parlamentarians#index', :as => :parlamentarians
  match "parlamentarians/new" => 'parlamentarians#new', :as => :new_parlamentarian
  match "parlamentarians/:rdf_uri" => 'parlamentarians#update', :as => :update_parlamentarian, :via => :put
  match "parlamentarians/:rdf_uri" => 'parlamentarians#destroy', :as => :destroy_parlamentarian, :via => :delete
  match "parlamentarians/:rdf_uri" => 'parlamentarians#show', :as => :parlamentarian
  match "parlamentarians/:rdf_uri/edit" => 'parlamentarians#edit', :as => :edit_parlamentarian

  match "rdf_interventions" => 'rdf_interventions#create', :via => :post
  match "rdf_interventions" => 'rdf_interventions#index', :as => :rdf_interventions
  match "rdf_interventions/new" => 'rdf_interventions#new', :as => :new_rdf_intervention
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#update', :as => :update_rdf_intervention, :via => :put
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#destroy', :as => :destroy_rdf_intervention, :via => :delete
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#show', :as => :rdf_intervention
  match "rdf_interventions/:rdf_uri/edit" => 'rdf_interventions#edit', :as => :edit_rdf_intervention

  match "parties" => 'parties#create', :via => :post
  match "parties" => 'parties#index', :as => :rdf_parties
  match "parties/new" => 'parties#new', :as => :new_rdf_party
  match "parties/:rdf_uri" => 'parties#update', :as => :update_rdf_party, :via => :put
  match "parties/:rdf_uri" => 'parties#destroy', :as => :destroy_rdf_party, :via => :delete
  match "parties/:rdf_uri" => 'parties#show', :as => :rdf_party
  match "parties/:rdf_uri/edit" => 'parties#edit', :as => :edit_rdf_party

  match "qualities" => 'qualities#create', :via => :post
  match "qualities" => 'qualities#index', :as => :rdf_qualities
  match "qualities/new" => 'qualities#new', :as => :new_rdf_quality
  match "qualities/:rdf_uri" => 'qualities#update', :as => :update_rdf_quality, :via => :put
  match "qualities/:rdf_uri" => 'qualities#destroy', :as => :destroy_rdf_quality, :via => :delete
  match "qualities/:rdf_uri" => 'qualities#show', :as => :rdf_quality
  match "qualities/:rdf_uri/edit" => 'qualities#edit', :as => :edit_rdf_quality

  match "participation_types" => 'participation_types#create', :via => :post
  match "participation_types" => 'participation_types#index', :as => :rdf_participation_types
  match "participation_types/new" => 'participation_types#new', :as => :new_rdf_participation_type
  match "participation_types/:rdf_uri" => 'participation_types#update', :as => :update_rdf_participation_type, :via => :put
  match "participation_types/:rdf_uri" => 'participation_types#destroy', :as => :destroy_rdf_participation_type, :via => :delete
  match "participation_types/:rdf_uri" => 'participation_types#show', :as => :rdf_participation_type
  match "participation_types/:rdf_uri/edit" => 'participation_types#edit', :as => :edit_rdf_participation_type

  get "home/index"
  match "home/show_empty" => "home#show_empty", :as => :mostrar_vacio
  match "home/show_admin" => "home#show_admin", :as => :mostrar_admin
  match "home/show_analist" => "home#show_analist", :as => :mostrar_analista
  match "home/show_qa_analist" => "home#show_qa_analist", :as => :mostrar_analista_qa
  match "home/show_planner" => "home#show_planner", :as => :mostrar_planificador
  match "home/show_ot/:ot_id" => "home#show_ot", :as => :mostrar_ot
  match "home/edit_ot/:ot_id" => "home#edit_ot", :as => :editar_ot
  match "home/update_ot" => "home#update_ot", :as => :actualizar_ot, :method => :post
  match "home/show_document/:frbr_manifestation_id" => "home#show_document", :as => :mostrar_documento
  match "home/show_am_result/:am_result_id" => "home#show_am_result", :as => :mostrar_resultado_ma
  match "home/create_observation" => "home#create_observation", :as => :create_observation, :method => :post
  match "home/new_ot" => "home#new_ot", :as => :home_new_ot
  match "home/create_new_ot" => "home#create_new_ot", :as => :create_new_ot, :method => :post
  match "home/clear_database" => "home#clear_database", :as => :clear_database

  match "home/filter_ots/" => "home#filter_ots", :as => :filter_ots

  match "marcado_documento/perform_work/:task_id/(:event)" => "marcado_documento#perform_work", :as => :marcado_documento_perform_work
  match "marcado_documento/realizar_marcaje_automatico" => "marcado_documento#realizar_marcaje_automatico", :as => :realizar_marcaje_automatico, :method => :post
  match "marcado_documento/save_xml_document" => "marcado_documento#save_xml_document", :as => :marcado_documento_save_xml_document, :method => :post
  match "marcado_documento/requiere_marcaje_automatico_event/:task_id" => "marcado_documento#requiere_marcaje_automatico_event", :as => :requiere_marcaje_automatico_event
  match "marcado_documento/no_requiere_marcaje_automatico_event/:task_id" => "marcado_documento#no_requiere_marcaje_automatico_event", :as => :no_requiere_marcaje_automatico_event
  match "marcado_documento/requiere_modificaciones_event/:task_id" => "marcado_documento#requiere_modificaciones_event", :as => :requiere_modificaciones_event
  match "marcado_documento/no_requiere_modificaciones_event/:task_id" => "marcado_documento#no_requiere_modificaciones_event", :as => :no_requiere_modificaciones_event
  match "marcado_documento/termina_correcciones_event/:task_id" => "marcado_documento#termina_correcciones_event", :as => :termina_correcciones_event
  match "marcado_documento/verifica_correcciones_event/:task_id" => "marcado_documento#verifica_correcciones_event", :as => :verifica_correcciones_event
  match "marcado_documento/termina_marcaje_automatico_event/:task_id" => "marcado_documento#termina_marcaje_automatico_event", :as => :termina_marcaje_automatico_event

  match "qa_documento/perform_work/:task_id/(:event)" => "qa_documento#perform_work", :as => :qa_documento_perform_work
  match "qa_documento/save_xml_document" => "qa_documento#save_xml_document", :as => :qa_documento_save_xml_document, :method => :post
  match "qa_documento/recibe_notificacion_event/:task_id" => "qa_documento#recibe_notificacion_event", :as => :recibe_notificacion_event
  match "qa_documento/comienza_validar_event/:task_id" => "qa_documento#comienza_validar_event", :as => :comienza_validar_event
  match "qa_documento/rechaza_event/:task_id" => "qa_documento#rechaza_event", :as => :rechaza_event
  match "qa_documento/aprueba_tarea_event/:task_id" => "qa_documento#aprueba_tarea_event", :as => :aprueba_tarea_event
  match "qa_documento/aprueba_ot_event/:task_id" => "qa_documento#aprueba_ot_event", :as => :aprueba_ot_event
  match "qa_documento/publica_documento_event/:task_id" => "qa_documento#publica_documento_event", :as => :publica_documento_event

  match "plan_cuenta/perform_work/:task_id/(:event)" => "plan_cuenta#perform_work", :as => :plan_cuenta_perform_work
  match "plan_cuenta/eligiendo_documento" => "plan_cuenta#eligiendo_documento"
  match "plan_cuenta/create_document" => "plan_cuenta#create_document", :as => :plan_cuenta_crear_documento, :method => :post
  match "plan_cuenta/create_asignar_tareas" => "plan_cuenta#create_asignar_tareas", :as => :crear_asignar_tareas, :method => :post
  match "plan_cuenta/create_notificar_analista" => "plan_cuenta#create_notificar_analista", :as => :crear_notificar_analista, :method => :post

  match "plan_diario/perform_work/:task_id/(:event)"=> "plan_diario#perform_work", :as => :plan_diario_perform_work
  match "plan_diario/eligiendo_documento" => "plan_diario#eligiendo_documento"
  match "plan_diario/en_marcaje_automatico" => "plan_diario#en_marcaje_automatico"
  match "plan_diario/evaluando_resultados" => "plan_diario#evaluando_resultados"
  match "plan_diario/planifica_asignar_tareas" => "plan_diario#planifica_asignar_tareas"
  match "plan_diario/asignando_tareas" => "plan_diario#asignando_tareas"
  match "plan_diario/notificar_equipos" => "plan_diario#notificar_equipos"
  match "plan_diario/create_document" => "plan_cuenta#create_document", :as => :plan_diario_crear_documento, :method => :post
  match "plan_diario/realizar_marcaje_automatico" => "plan_diario#realizar_marcaje_automatico", :as => :marcaje_automatico_plan_diario, :method => :post
  match "plan_diario/create_dividir_tareas" => "plan_diario#create_dividir_tareas", :as => :create_dividir_tareas, :method => :post

app/views/plan_poblamiento/_poblamiento_param_form.html.erb
 <%= form_for(@poblamiento_param, :url => create_poblamiento_param) do |f| %>
	<% if @poblamiento_param.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@poblamiento_param.errors.count, "error") %> prohibited this poblamiento_param from being saved:</h2>
			<ul>
				<% @poblamiento_param.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field invisible">
		<%= f.label :ot_id, "Ot" %><br />
	    <%= collection_select(:poblamiento_param, :ot_id, Ot.all, :id, :name) %>
	</div>

	<div class="field">
		<%= f.label :frbr_entity_id, "Organismo de origen" %><br />
	    <%= collection_select(:poblamiento_param, :frbr_entity_id, FrbrEntity.all, :id, :name) %>
	</div>

	<div class="field">
		<%= f.label :priority_id, "Prioridad" %><br />
	    <%= collection_select(:poblamiento_param, :priority_id, Priority.all, :id, :name) %>
	</div>

	<div class="field">
		<%= f.label :intermediary_id, "Intermediario" %><br />
	    <%= collection_select(:poblamiento_param, :intermediary_id, Intermediary.all, :id, :name) %>
	</div>

	<div class="field">
		<%= f.label :location_id, "Localización" %><br />
	    <%= collection_select(:poblamiento_param, :location_id, PoblamientoImportLocation.all, :id, :name) %>
	</div>

	<div class="field">
		<%= f.label :file_format_id, "Formato del fichero" %><br />
	    <%= collection_select(:poblamiento_param, :file_format_id, PoblamientoFileFormat.all, :id, :format_spec) %>
	</div>

	<div class="field">
		<%= f.label :start_date, "Desde" %><br />
		<%= f.date_select :start_date %>
	</div>

	<div class="field">
		<%= f.label :end_date, "Hasta" %><br />
		<%= f.date_select :end_date %>
	</div>

	<div class="actions">
		<%= f.submit "Continuar" %>
	</div>
<% end %>

app/views/plan_poblamiento/determina_periodo.html.erb
<%= render "shared/work_header" %>

<%= render :partial => "poblamiento_param_form", :locals => { :create_poblamiento_param => plan_poblamiento_create_params_path }%>

app/views/plan_poblamiento/genera_ots.html.erb
<%= render "shared/work_header" %>

<table>
	<tr>
		<th>Organismo de origen</th>
		<td><%= @poblamiento_param.frbr_bcn_type.name %></td>
	<tr>
	<tr>
		<th>Tipo de documento</th>
		<td><%= @poblamiento_param.frbr_entity.name %></td>
	<tr>
	<tr>
		<th>Prioridad</th>
		<td><%= @poblamiento_param.priority.name %></td>
	<tr>
	<tr>
		<th>Desde</th>
		<td><%= @poblamiento_param.start_date %></td>
	<tr>
	<tr>
		<th>Hasta</th>
		<td><%= @poblamiento_param.end_date %></td>
	<tr>
</table>
	
<%= form_tag(plan_poblamiento_create_genera_ots_path) %>
	<%= hidden_field_tag(:ot_id, @ot.id) %>

	<div class="actions">
		<%= submit_tag "Generar OTs" %>
	</div>
</form>

app/views/plan_poblamiento/modificar_periodo.html.erb
<%= render "shared/work_header" %>

<%= render :partial => "poblamiento_param_form", :locals => { :create_poblamiento_param => plan_poblamiento_update_params_path }%>

app/views/plan_poblamiento/revisando_parametros.html.erb
<%= render "shared/work_header" %>

<table>
	<tr>
		<th>Organismo de origen</th>
		<td><%= @poblamiento_param.frbr_entity.name %></td>
	</tr>
	<tr>
		<th>Prioridad</th>
		<td><%= @poblamiento_param.priority.name %></td>
	</tr>
	<tr>
		<th>Intermediario</th>
		<td><%= @poblamiento_param.intermediary.name unless @poblamiento_param.intermediary.nil? %></td>
	</tr>
	<tr>
		<th>Localización</th>
		<td><%= @poblamiento_param.location.name %></td>
	</tr>
	<tr>
		<th>Formato</th>
		<td><%= @poblamiento_param.file_format.format_spec %></td>
	</tr>
	<tr>
		<th>Desde</th>
		<td><%= @poblamiento_param.start_date %></td>
	</tr>
	<tr>
		<th>Hasta</th>
		<td><%= @poblamiento_param.end_date %></td>
	</tr>
</table>

<h2>Resumen</h2>
<table>
	<thead>
		<tr>
			<th colspan="2">Legislaturas</th>
			<th colspan="2">Sesiones</th>
			<th colspan="4">Procesamiento</th>
		</tr>
		<tr>
			<th>Desde</th>
			<th>Hasta</th>
			<th>Desde</th>
			<th>Hasta</th>
			<th>Total</th>
			<th>Ninguno</th>
			<th>Parcial</th>
			<th>Completo</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @poblamiento_generated_params.earliest_legislature(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.latest_legislature(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.earliest_session(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.latest_session(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.total_processing(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.number_no_processing(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.number_partial(@ot.id) %></td>
			<td><%= @poblamiento_generated_params.number_complete(@ot.id) %></td>
		</tr>
	</tbody>
</table>

<h2>OTs a generar</h2>
<table>
	<thead>
		<tr>
			<th>Legislatura</th>
			<th>Sesión</th>
			<th>Fecha</th>
			<th>Procesamiento</th>
		</tr>
	</thead>
	<tbody>
		<% @poblamiento_generated_params.each do |pgp| %>
		<tr>
			<td><%= pgp.legislature.to_s %></td>
			<td><%= pgp.session.to_s %></td>
			<td><%= pgp.session_date %></td>
			<td><%= pgp.processing %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= form_tag(plan_poblamiento_create_genera_ots_path) %>
	<%= hidden_field_tag(:ot_id, @ot.id) %>

	<div class="actions">
		<%= submit_tag "Generar OTs" %>
	</div>
</form>

|&nbsp;<%= link_to "Modificar parametros", plan_poblamiento_rechazar_parametros_event_path(@task.id) %>&nbsp;|

app/views/plan_poblamiento/termina_poblamiento.html.erb
<%= render "shared/work_header" %>