config/routes.rb
  resources :frbr_expressions
  resources :frbr_document_types
  resources :frbr_works
  resources :frbr_bcn_types
  resources :frbr_entities
  resources :task_types
  resources :roles
  resources :priorities
  resources :ot_types
  resources :ots
  resources :tasks
  devise_for :users

  match "parlamentarians" => 'parlamentarians#create', :via => :post
  match "parlamentarians" => 'parlamentarians#index', :as => :parlamentarians
  match "parlamentarians/new" => 'parlamentarians#new', :as => :new_parlamentarian
  match "parlamentarians/:rdf_uri" => 'parlamentarians#update', :as => :update_parlamentarian, :via => :put
  match "parlamentarians/:rdf_uri" => 'parlamentarians#destroy', :as => :destroy_parlamentarian, :via => :delete
  match "parlamentarians/:rdf_uri" => 'parlamentarians#show', :as => :parlamentarian
  match "parlamentarians/:rdf_uri/edit" => 'parlamentarians#edit', :as => :edit_parlamentarian

  match "rdf_interventions" => 'rdf_interventions#create', :via => :post
  match "rdf_interventions" => 'rdf_interventions#index', :as => :rdf_interventions
  match "rdf_interventions/new" => 'rdf_interventions#new', :as => :new_rdf_intervention
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#update', :as => :update_rdf_intervention, :via => :put
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#destroy', :as => :destroy_rdf_intervention, :via => :delete
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#show', :as => :rdf_intervention
  match "rdf_interventions/:rdf_uri/edit" => 'rdf_interventions#edit', :as => :edit_rdf_intervention

  match "parties" => 'parties#create', :via => :post
  match "parties" => 'parties#index', :as => :rdf_parties
  match "parties/new" => 'parties#new', :as => :new_rdf_party
  match "parties/:rdf_uri" => 'parties#update', :as => :update_rdf_party, :via => :put
  match "parties/:rdf_uri" => 'parties#destroy', :as => :destroy_rdf_party, :via => :delete
  match "parties/:rdf_uri" => 'parties#show', :as => :rdf_party
  match "parties/:rdf_uri/edit" => 'parties#edit', :as => :edit_rdf_party

  match "qualities" => 'qualities#create', :via => :post
  match "qualities" => 'qualities#index', :as => :rdf_qualities
  match "qualities/new" => 'qualities#new', :as => :new_rdf_quality
  match "qualities/:rdf_uri" => 'qualities#update', :as => :update_rdf_quality, :via => :put
  match "qualities/:rdf_uri" => 'qualities#destroy', :as => :destroy_rdf_quality, :via => :delete
  match "qualities/:rdf_uri" => 'qualities#show', :as => :rdf_quality
  match "qualities/:rdf_uri/edit" => 'qualities#edit', :as => :edit_rdf_quality

  match "participation_types" => 'participation_types#create', :via => :post
  match "participation_types" => 'participation_types#index', :as => :rdf_participation_types
  match "participation_types/new" => 'participation_types#new', :as => :new_rdf_participation_type
  match "participation_types/:rdf_uri" => 'participation_types#update', :as => :update_rdf_participation_type, :via => :put
  match "participation_types/:rdf_uri" => 'participation_types#destroy', :as => :destroy_rdf_participation_type, :via => :delete
  match "participation_types/:rdf_uri" => 'participation_types#show', :as => :rdf_participation_type
  match "participation_types/:rdf_uri/edit" => 'participation_types#edit', :as => :edit_rdf_participation_type

  get "home/index"
  match "home/show_empty" => "home#show_empty", :as => :mostrar_vacio
  match "home/show_admin" => "home#show_admin", :as => :mostrar_admin
  match "home/show_analist" => "home#show_analist", :as => :mostrar_analista
  match "home/show_qa_analist" => "home#show_qa_analist", :as => :mostrar_analista_qa
  match "home/show_planner" => "home#show_planner", :as => :mostrar_planificador
  match "home/show_ot/:ot_id" => "home#show_ot", :as => :mostrar_ot
  match "home/edit_ot/:ot_id" => "home#edit_ot", :as => :editar_ot
  match "home/update_ot" => "home#update_ot", :as => :actualizar_ot, :method => :post
  match "home/show_document/:frbr_manifestation_id" => "home#show_document", :as => :mostrar_documento
  match "home/show_am_result/:am_result_id" => "home#show_am_result", :as => :mostrar_resultado_ma
  match "home/create_observation" => "home#create_observation", :as => :create_observation, :method => :post
  match "home/new_ot" => "home#new_ot", :as => :home_new_ot
  match "home/create_new_ot" => "home#create_new_ot", :as => :create_new_ot, :method => :post
  match "home/clear_database" => "home#clear_database", :as => :clear_database

  match "home/filter_ots/" => "home#filter_ots", :as => :filter_ots

  match "marcado_documento/perform_work/:task_id/(:event)" => "marcado_documento#perform_work", :as => :marcado_documento_perform_work
  match "marcado_documento/realizar_marcaje_automatico" => "marcado_documento#realizar_marcaje_automatico", :as => :realizar_marcaje_automatico, :method => :post
  match "marcado_documento/save_xml_document" => "marcado_documento#save_xml_document", :as => :marcado_documento_save_xml_document, :method => :post
  match "marcado_documento/requiere_marcaje_automatico_event/:task_id" => "marcado_documento#requiere_marcaje_automatico_event", :as => :requiere_marcaje_automatico_event
  match "marcado_documento/no_requiere_marcaje_automatico_event/:task_id" => "marcado_documento#no_requiere_marcaje_automatico_event", :as => :no_requiere_marcaje_automatico_event
  match "marcado_documento/requiere_modificaciones_event/:task_id" => "marcado_documento#requiere_modificaciones_event", :as => :requiere_modificaciones_event
  match "marcado_documento/no_requiere_modificaciones_event/:task_id" => "marcado_documento#no_requiere_modificaciones_event", :as => :no_requiere_modificaciones_event
  match "marcado_documento/termina_correcciones_event/:task_id" => "marcado_documento#termina_correcciones_event", :as => :termina_correcciones_event
  match "marcado_documento/verifica_correcciones_event/:task_id" => "marcado_documento#verifica_correcciones_event", :as => :verifica_correcciones_event
  match "marcado_documento/termina_marcaje_automatico_event/:task_id" => "marcado_documento#termina_marcaje_automatico_event", :as => :termina_marcaje_automatico_event

  match "qa_documento/perform_work/:task_id/(:event)" => "qa_documento#perform_work", :as => :qa_documento_perform_work
  match "qa_documento/save_xml_document" => "qa_documento#save_xml_document", :as => :qa_documento_save_xml_document, :method => :post
  match "qa_documento/recibe_notificacion_event/:task_id" => "qa_documento#recibe_notificacion_event", :as => :recibe_notificacion_event
  match "qa_documento/comienza_validar_event/:task_id" => "qa_documento#comienza_validar_event", :as => :comienza_validar_event
  match "qa_documento/rechaza_event/:task_id" => "qa_documento#rechaza_event", :as => :rechaza_event
  match "qa_documento/aprueba_tarea_event/:task_id" => "qa_documento#aprueba_tarea_event", :as => :aprueba_tarea_event
  match "qa_documento/aprueba_ot_event/:task_id" => "qa_documento#aprueba_ot_event", :as => :aprueba_ot_event
  match "qa_documento/publica_documento_event/:task_id" => "qa_documento#publica_documento_event", :as => :publica_documento_event

  match "plan_cuenta/perform_work/:task_id/(:event)" => "plan_cuenta#perform_work", :as => :plan_cuenta_perform_work
  match "plan_cuenta/eligiendo_documento" => "plan_cuenta#eligiendo_documento"
  match "plan_cuenta/create_document" => "plan_cuenta#create_document", :as => :plan_cuenta_crear_documento, :method => :post
  match "plan_cuenta/create_asignar_tareas" => "plan_cuenta#create_asignar_tareas", :as => :crear_asignar_tareas, :method => :post
  match "plan_cuenta/create_notificar_analista" => "plan_cuenta#create_notificar_analista", :as => :crear_notificar_analista, :method => :post

  match "plan_diario/perform_work/:task_id/(:event)"=> "plan_diario#perform_work", :as => :plan_diario_perform_work
  match "plan_diario/eligiendo_documento" => "plan_diario#eligiendo_documento"
  match "plan_diario/en_marcaje_automatico" => "plan_diario#en_marcaje_automatico"
  match "plan_diario/evaluando_resultados" => "plan_diario#evaluando_resultados"
  match "plan_diario/planifica_asignar_tareas" => "plan_diario#planifica_asignar_tareas"
  match "plan_diario/asignando_tareas" => "plan_diario#asignando_tareas"
  match "plan_diario/notificar_equipos" => "plan_diario#notificar_equipos"
  match "plan_diario/create_document" => "plan_cuenta#create_document", :as => :plan_diario_crear_documento, :method => :post
  match "plan_diario/realizar_marcaje_automatico" => "plan_diario#realizar_marcaje_automatico", :as => :marcaje_automatico_plan_diario, :method => :post
  match "plan_diario/create_dividir_tareas" => "plan_diario#create_dividir_tareas", :as => :create_dividir_tareas, :method => :post
  match "plan_diario/agregar_tarea/:task_id" => "plan_diario#agregar_tarea", :as => :agregar_tarea_marcado_diario
  match "plan_diario/create_asignar_tareas" => "plan_diario#create_asignar_tareas", :as => :crear_asignar_tareas_diario, :method => :post
  match "plan_diario/create_notificar_equipos" => "plan_diario#create_notificar_equipos", :as => :create_notificar_equipos, :method => :post
  match "plan_diario/termina_evaluacion_event/:task_id" => "plan_diario#termina_evaluacion_event", :as => :termina_evaluacion_event
  match "plan_diario/decide_dividir_event/:task_id" => "plan_diario#decide_dividir_event", :as => :decide_dividir_event
  match "plan_diario/decide_no_dividir_event/:task_id" => "plan_diario#decide_no_dividir_event", :as => :decide_no_dividir_event

  match "plan_diario_post/perform_work/:task_id/(:event)"=> "plan_diario_post#perform_work", :as => :plan_diario_post_perform_work
  match "plan_diario_post/esperando_notificacion_analista"=> "plan_diario_post#esperando_notificacion_analista", :as => :plan_diario_post_esperando_notificacion_analista
  match "plan_diario_post/verificando_completitud"=> "plan_diario_post#verificando_completitud", :as => :plan_diario_post_verificando_completitud

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_menu_section

  def set_menu_section
    @accordion_section = 0
  end

  # Dispatch according to who is logged on
  def index
    if current_user.nil?
      show_empty
    elsif current_user.role.id == 1
      show_analist
    elsif current_user.role.id == 2
      show_qa_analist
    elsif current_user.role.id == 3
      show_planner
    elsif current_user.role.id == 5
      show_admin
    else
      show_empty
    end
  end

  def generate_audit(ot)
    params = Hash.new
    params[:user_id] = current_user.id
    params[:role_id] = current_user.role.id
    params[:ot_id] = ot.id
    params[:description] = "Creacion de nueva OT tipo #{ot.ot_type.name}"
    log_entry = Audit.new(params)
    log_entry.save
  end

  def new_ot
    screen_name("Admin-Nueva-OT")
    @ot = Ot.new
    @ot.created_by = current_user.id
    @ot.target_date = DateTime.now + 2

    observation = Observation.new
    observation.user_id = current_user.id
    @ot.observations << observation

    respond_to do |format|
      format.html # new_ot.html.erb
    end
  end

  # POST /create_new_ot
  def create_new_ot
    params[:ot].delete(:observations_attributes) if params[:ot][:observations_attributes]["0"][:contents].length == 0
    @ot = Ot.new(params[:ot])

    respond_to do |format|
      if @ot.save
        generate_audit(@ot)
        @ot.create_tasks(current_user)
        format.html { redirect_to root_path, notice: 'La OT fue creada sin dificultades.' }
      else
        format.html { render action: "new_ot" }
      end
    end
  end

  # Nobody logged on -- show empty screen
  def show_empty
    screen_name("Inicial")

    respond_to do |format|
      format.html { render action: "show_empty" }
      format.json { head :ok }
    end
  end

  def distribute_ots
    @tasks_incoming = Array.new
    @tasks_work = Array.new
    @ots_sent = Array.new
    ots_covered = Array.new
    Ot.order("updated_at DESC").each do |ot|
      if !ot.current_task.nil?
        ot.tasks.each do |task|
          if task.is_active? && task.current_user_id == current_user.id && ot.read == false
            @tasks_incoming << task
            ots_covered << ot
          elsif task.is_active? && task.current_user_id == current_user.id && task.ot.read == true && task.ot.completed_on.nil?
            @tasks_work << task
            ots_covered << ot
          end
        end
        if (ot.owner.id == current_user.id || ot.has_been_worked_on_by(current_user.id)) && !ots_covered.include?(ot)
          @ots_sent << ot
        end
      end
    end
  end

  # Show analist's trays
  def show_analist
    screen_name("Inicial-Analista")

    distribute_ots

    respond_to do |format|
      format.html { render action: "show_analist" }
      format.json { head :ok }
    end
  end

  # Show QA analist's trays
  def show_qa_analist
    screen_name("Inicial-Analista-QA")

    distribute_ots

    respond_to do |format|
      format.html { render action: "show_qa_analist" }
      format.json { head :ok }
    end
  end

  # Show planner's trays
  def show_planner
    screen_name("Inicial-Planificador")

    distribute_ots

    respond_to do |format|
      format.html { render action: "show_planner" }
      format.json { head :ok }
    end
  end

  # Show admin's trays, similar to planner's
  def show_admin
    screen_name("Inicial-Admin")

    distribute_ots

    respond_to do |format|
      format.html { render action: "show_admin" }
      format.json { head :ok }
    end
  end

  # Show a specific OT
  def show_ot
    screen_name("Mostrar-OT")

    @ot = Ot.find(params[:ot_id])
    @ot.mark_read

    @am_results = AmResult.where("ot_id = #{@ot.id}").order("run_date DESC")
    @observations = Observation.where("ot_id = #{@ot.id}")
    @log = Audit.where("ot_id = #{@ot.id}").order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @versions = TargetDocumentVersion.where("ot_id = #{@ot.id}").order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

    if current_user.role.id == 3 || current_user.role.id == 5
      @task = @ot.current_task
    end
  end

  # GET edit_ot
  def edit_ot
    screen_name("Editar-OT")

    @ot = Ot.find(params[:ot_id])
    @task = @ot.current_task
  end

  # POST update_ot
  def update_ot
    @ot = Ot.find(params[:ot][:id])

    respond_to do |format|
      if @ot.update_attributes(params[:ot])
        format.html { redirect_to root_path, notice: 'Ot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit_ot" }
        format.json { render json: @ot.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_document
    screen_name("Mostrar-Documento")

    @document = FrbrManifestation.find(params[:frbr_manifestation_id])
  end

  def show_am_result
    screen_name("Mostrar-Resultado-MA")

    @am_result = AmResult.find(params[:am_result_id])
    @ot = Ot.find(@am_result.ot_id)
    @task = @ot.current_task
  end

  def create_observation
    params[:observation][:user_id] = current_user.id
    @observation = Observation.new(params[:observation])

    @ot = Ot.find(params[:observation][:ot_id])
    @am_results = AmResult.where("ot_id = #{@ot.id}").order("run_date DESC")
    @observations = Observation.where("ot_id = #{@ot.id}")
    @log = Audit.where("ot_id = #{@ot.id}").order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @versions = TargetDocumentVersion.where("ot_id = #{@ot.id}").order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      if @observation.save
        format.html { render action: "show_ot" }
        format.json { render json: @observation, status: :created, location: @observation }
      else
        format.html { render action: "show_ot" }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  def clear_database
    Audit.delete_all
    AmConfiguration.delete_all
    AmObservation.delete_all
    AmResult.delete_all
    FrbrManifestation.delete_all
    FrbrExpression.delete_all
    FrbrWork.delete_all
    TargetDocumentVersion.delete_all
    Task.delete_all
    Observation.delete_all
    PoblamientoParam.delete_all
    PoblamientoGeneratedParam.delete_all
    TpParameter.delete_all
    TpGeneratedParam.delete_all
    Ot.delete_all

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Base de datos limpiada.' }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_current_command_bar.html.erb
<% if current_user.role.id == 1 || current_user.role.id == 3 %>
	<div class="command-bar">
		<% if current_user.role.id == 1 %>
			|&nbsp;
			<%= link_to "Marcado automático", root_path %>
			&nbsp;|
		<% elsif current_user.role.id == 3 %>
			|&nbsp;
			<%= link_to "Eliminar", root_path %>
			&nbsp;|&nbsp;
			<%= link_to "Asignar", root_path %>
			&nbsp;|&nbsp;
			<%= link_to "Notificar analista", root_path %>
			&nbsp;|
		<% end %>
	</div>
<% end %>

app/views/home/_new_ot_form.html.erb
<%= form_for(@ot, :url => create_new_ot_path) do |f| %>
	<% if @ot.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@ot.errors.count, "error") %> prohibited this ot from being saved:</h2>
			<ul>
				<% @ot.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
	    <%= f.label(:ot_type_id, 'Tipo') %><br />
	    <%= f.select :ot_type_id, OtType.order("name ASC").map { |t| [t.name, t.id] }, :selected => @ot.ot_type_id %>
	</div>

	<div class="field invisible">
	    <%= f.label(:ot_state_id, 'Estado') %><br />
	    <%= f.select :ot_state_id, OtState.all.map { |s| [s.name, s.id] }, :selected => @ot.ot_state_id %>
	</div>

	<div class="field">
	    <%= f.label(:priority_id, 'Prioridad') %><br />
	    <%= f.select :priority_id, Priority.all.map { |p| [p.name, p.id] }, :selected => @ot.priority_id %>
	</div>

	<div class="field invisible">
	    <%= f.label(:created_by, 'Creada por') %><br />
	    <%= f.select :created_by, User.all.map { |u| [u.email, u.id] }, :selected => @ot.created_by %>
	</div>

	<div class="field">
	    <%= f.label(:by_request_of, 'A pedido de') %><br />
	    <%= f.text_field(:by_request_of) %>
	</div>

	<div class="field">
		<%= f.label :target_date, "Fecha de entrega" %><br />
		<%= f.datetime_select :target_date %>
	</div>

	<%= f.fields_for :observations do | observation_form | %>
		<div class="field invisible">
			<%= observation_form.label :user_id, "Usuario" %><br />
		    <%= observation_form.text_field :user_id %>
		</div>

		<div class="field">
			<%= observation_form.label :observation_type_id, "Tipo de observación" %><br />
		    <%= observation_form.select :observation_type_id, ObservationType.all.map { |o| [o.name, o.id] } %>
		</div>

		<div class="field">
			<%= observation_form.label :contents, "Observaciones" %><br />
			<%= observation_form.text_area :contents %>
		</div>
	<% end %>

	<div class="actions">
		<%= f.submit "Generar" %>
	</div>
<% end %>

app/views/home/_ot_filter.html.erb
<div class="toggler">
	<a href="#" id="<%= show_button_id %>" class="ui-state-default ui-corner-all">Filtro</a>
	<div id="<%= filter_selector_id %>">
		<%= form_tag(filter_ots_path) %>
			<fieldset>
				<div class="inline-field">
					<%= label_tag :search, "Búsqueda texto libre: " %>&nbsp;
					<%= text_field_tag "filter[search]", "", :size => "80" %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :organism, "Organismo: " %>&nbsp;
					<%= select_tag "filter[organism]", options_from_collection_for_select(FrbrEntity.all, :id, :name), { :include_blank => true } %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :legislature, "Legislatura: " %>&nbsp;
					<%= text_field_tag "filter[legislature]" %>
				</div>
				<div class="clear">

				<div class="inline-field">
					<%= label_tag :serial_number, "Número de serie: " %>&nbsp;
					<%= text_field_tag "filter[serial_number]" %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :ot_type, "Tipo de OT: " %>&nbsp;
					<%= select_tag "filter[ot_type]", options_from_collection_for_select(OtType.all, :id, :name), { :include_blank => true } %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :document_type, "Tipo de Documento: " %>&nbsp;
					<%= select_tag "filter[document_type]", options_from_collection_for_select(FrbrBcnType.all, :id, :name), { :include_blank => true } %>
				</div>
				<div class="clear">

				<div class="inline-field">
					<%= label_tag :priority, "Prioridad: " %>&nbsp;
					<%= select_tag "filter[priority]", options_from_collection_for_select(Priority.all, :id, :name), { :include_blank => true } %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :assigned_to, "Asignada a: " %>&nbsp;
					<%= select_tag "filter[assigned_to]", options_from_collection_for_select(User.all, :id, :user_name), { :include_blank => true } %>
				</div>
				<div class="inline-field">
					&nbsp;&nbsp;
					<%= label_tag :state, "Estado: " %>&nbsp;
					<%= select_tag "filter[state]", options_for_select([['En proceso', 1], ['Suspendida', 2], ['Completa', 3]]), { :include_blank => true } %>
				</div>
				<div class="clear">

				<fieldset class="date-range-fieldset">
					<div class="inline-field">
						<%= check_box_tag :session %>&nbsp;
						<%= label_tag :session, "Filtrar por fecha de sesión " %><br />
						<%= label_tag :session_from, "Desde: " %>&nbsp;
						<%= select_date Date.today, :prefix => :session_start_date %><br />
						<%= label_tag :session_to, "Hasta: " %>&nbsp;
						<%= select_date Date.today, :prefix => :session_end_date %>
					</div>
				</fieldset>
				<fieldset class="date-range-fieldset">
					<div class="inline-field">
						<%= check_box_tag :publication_date %>&nbsp;
						<%= label_tag :publication_date, "Filtrar por fecha de publicación " %><br />
						<%= label_tag :publication_date_from, "Desde: " %>&nbsp;
						<%= select_date Date.today, :prefix => :publication_date_start_date %><br />
						<%= label_tag :publication_date_to, "Hasta: " %>&nbsp;
						<%= select_date Date.today, :prefix => :publication_date_end_date %>
					</div>
				</fieldset>
				<fieldset class="date-range-fieldset">
					<div class="inline-field">
						<%= check_box_tag :creation_date %>&nbsp;
						<%= label_tag :creation_date, "Filtrar por fecha de creación " %><br />
						<%= label_tag :creation_date_from, "Desde: " %>&nbsp;
						<%= select_date Date.today, :prefix => :creation_date_start_date %><br />
						<%= label_tag :creation_date_to, "Hasta: " %>&nbsp;
						<%= select_date Date.today, :prefix => :creation_date_end_date %>
					</div>
				</fieldset>
				<fieldset class="date-range-fieldset">
					<div class="inline-field">
						<%= check_box_tag :update_date %>&nbsp;
						<%= label_tag :update_date, "Filtrar por fecha de actualización " %><br />
						<%= label_tag :update_date_from, "Desde: " %>&nbsp;
						<%= select_date Date.today, :prefix => :update_date_start_date %><br />
						<%= label_tag :update_date_to, "Hasta: " %>&nbsp;
						<%= select_date Date.today, :prefix => :update_date_end_date %>
					</div>
				</fieldset>
				<div class="clear">
				<div class="dummy-actions">
					<%= submit_tag "Filtrar" %>
				</div>
			</fieldset>
		</form>
	</div>
</div>

app/views/home/_ot_form.html.erb
<%= form_for(@ot, :url => actualizar_ot_path) do |f| %>
	<% if @ot.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@ot.errors.count, "error") %> prohibited this ot from being saved:</h2>
			<ul>
				<% @ot.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field invisible">
	    <%= f.label(:id) %><br />
	    <%= f.text_field(:id) %>
	</div>

	<div class="field invisible">
	    <%= f.label(:ot_type_id, 'Tipo') %><br />
	    <%= collection_select(:ot, :ot_type_id, OtType.order("name ASC"), :id, :name) %>
	</div>

	<div class="field">
	    <%= f.label(:priority_id, 'Prioridad') %><br />
	    <%= collection_select(:ot, :priority_id, Priority.all, :id, :name) %>
	</div>

	<div class="field invisible">
	    <%= f.label(:created_by, 'Creada por') %><br />
	    <%= collection_select(:ot, :created_by, User.all, :id, :email) %>
	</div>

	<div class="field">
	    <%= f.label(:by_request_of, 'A pedido de') %><br />
	    <%= f.text_field(:by_request_of) %>
	</div>

	<div class="field">
		<%= f.label :target_date, "Fecha de entrega" %><br />
		<%= f.datetime_select :target_date %>
	</div>

	<div class="actions">
		<%= f.submit "Actualizar" %>
	</div>
<% end %>

app/views/home/_sent_command_bar.html.erb
<% if current_user.role.id == 3 %>
	<div class="command-bar">
		|&nbsp;
		<%= link_to "Reasignar", root_path %>
		&nbsp;|
	</div>
<% end %>

app/views/home/index.html.erb
<h1>Bandeja de entrada</h1>

<table>
	<thead>
		<tr>
			<th>OT</th>
			<th>Prioridad</th>
			<th>Creada el</th>
			<th>Completada el</th>
		</tr>
	</thead>
	<tbody>
	<% @ots.each do |ot| %>
		<tr>
			<td><%= link_to ot.name, mostrar_ot_path(ot.id) %></td>
			<td><%= ot.priority.name %></td>
			<td><%= ot.created_on %></td>
			<td><%= ot.completed_on %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/home/show_analist.html.erb
<%= render :partial => "trays" %>

app/views/home/show_empty.html.erb
<h1 class="initial-message">Bienvenido al Sistema de Gestión de la Biblioteca del Congreso Nacional</h1>

app/views/home/show_planner.html.erb
<%= render :partial => "trays" %>