config/routes.rb
Bcn::Application.routes.draw do  
  match "trabajo_parlamentario/index" => "trabajo_parlamentario#index", :as => :trabajo_parlamentario
  match "trabajo_parlamentario/create" => "trabajo_parlamentario#create", :via => :post, :as => :create_trabajo_parlamentario

  resources :bitacoras
  resources :tramite_normativos
  resources :tramite_constitucionals
  resources :debate_types
  resources :tp_generated_params
  resources :taxonomy_terms
  resources :taxonomy_categories
  resources :tp_parameters
  resources :default_users_by_ot_types
  resources :am_module_configurations
  resources :poblamiento_generated_params
  resources :poblamiento_import_locations
  resources :poblamiento_file_formats
  resources :doc_type_am_configurations
  resources :task_transitions
  resources :poblamiento_params
  resources :observation_types
  resources :target_document_versions
  resources :markup_tools
  resources :am_configurations
  resources :am_observations
  resources :am_run_observation_types
  resources :am_results
  resources :intermediaries
  resources :delivery_methods
  resources :observations
  resources :ot_states
  resources :audits
  resources :frbr_manifestations
  resources :frbr_expressions
  resources :frbr_document_types
  resources :frbr_works
  resources :frbr_bcn_types
  resources :frbr_entities
  resources :task_types
  resources :roles
  resources :priorities
  resources :ot_types
  resources :ots
  resources :tasks
  devise_for :users

  match "parlamentarians" => 'parlamentarians#create', :via => :post
  match "parlamentarians" => 'parlamentarians#index', :as => :parlamentarians
  match "parlamentarians/new" => 'parlamentarians#new', :as => :new_parlamentarian
  match "parlamentarians/:rdf_uri" => 'parlamentarians#update', :as => :update_parlamentarian, :via => :put
  match "parlamentarians/:rdf_uri" => 'parlamentarians#destroy', :as => :destroy_parlamentarian, :via => :delete
  match "parlamentarians/:rdf_uri" => 'parlamentarians#show', :as => :parlamentarian
  match "parlamentarians/:rdf_uri/edit" => 'parlamentarians#edit', :as => :edit_parlamentarian

  match "rdf_interventions" => 'rdf_interventions#create', :via => :post
  match "rdf_interventions" => 'rdf_interventions#index', :as => :rdf_interventions
  match "rdf_interventions/new" => 'rdf_interventions#new', :as => :new_rdf_intervention
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#update', :as => :update_rdf_intervention, :via => :put
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#destroy', :as => :destroy_rdf_intervention, :via => :delete
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#show', :as => :rdf_intervention
  match "rdf_interventions/:rdf_uri/edit" => 'rdf_interventions#edit', :as => :edit_rdf_intervention

  match "parties" => 'parties#create', :via => :post
  match "parties" => 'parties#index', :as => :rdf_parties
  match "parties/new" => 'parties#new', :as => :new_rdf_party
  match "parties/:rdf_uri" => 'parties#update', :as => :update_rdf_party, :via => :put
  match "parties/:rdf_uri" => 'parties#destroy', :as => :destroy_rdf_party, :via => :delete
  match "parties/:rdf_uri" => 'parties#show', :as => :rdf_party
  match "parties/:rdf_uri/edit" => 'parties#edit', :as => :edit_rdf_party

  match "qualities" => 'qualities#create', :via => :post
  match "qualities" => 'qualities#index', :as => :rdf_qualities
  match "qualities/new" => 'qualities#new', :as => :new_rdf_quality
  match "qualities/:rdf_uri" => 'qualities#update', :as => :update_rdf_quality, :via => :put
  match "qualities/:rdf_uri" => 'qualities#destroy', :as => :destroy_rdf_quality, :via => :delete
  match "qualities/:rdf_uri" => 'qualities#show', :as => :rdf_quality
  match "qualities/:rdf_uri/edit" => 'qualities#edit', :as => :edit_rdf_quality

  match "participation_types" => 'participation_types#create', :via => :post
  match "participation_types" => 'participation_types#index', :as => :rdf_participation_types
  match "participation_types/new" => 'participation_types#new', :as => :new_rdf_participation_type
  match "participation_types/:rdf_uri" => 'participation_types#update', :as => :update_rdf_participation_type, :via => :put
  match "participation_types/:rdf_uri" => 'participation_types#destroy', :as => :destroy_rdf_participation_type, :via => :delete
  match "participation_types/:rdf_uri" => 'participation_types#show', :as => :rdf_participation_type
  match "participation_types/:rdf_uri/edit" => 'participation_types#edit', :as => :edit_rdf_participation_type

  get "home/index"
  match "home/show_empty" => "home#show_empty", :as => :mostrar_vacio
  match "home/show_admin" => "home#show_admin", :as => :mostrar_admin
  match "home/show_analist" => "home#show_analist", :as => :mostrar_analista
  match "home/show_qa_analist" => "home#show_qa_analist", :as => :mostrar_analista_qa
  match "home/show_planner" => "home#show_planner", :as => :mostrar_planificador
  match "home/show_ot/:ot_id" => "home#show_ot", :as => :mostrar_ot
  match "home/edit_ot/:ot_id" => "home#edit_ot", :as => :editar_ot
  match "home/update_ot" => "home#update_ot", :as => :actualizar_ot, :method => :post
  match "home/show_document/:frbr_manifestation_id" => "home#show_document", :as => :mostrar_documento
  match "home/show_am_result/:am_result_id" => "home#show_am_result", :as => :mostrar_resultado_ma
  match "home/create_observation" => "home#create_observation", :as => :create_observation, :method => :post
  match "home/new_ot" => "home#new_ot", :as => :home_new_ot
  match "home/create_new_ot" => "home#create_new_ot", :as => :create_new_ot, :method => :post
  match "home/clear_database" => "home#clear_database", :as => :clear_database

  match "home/filter_ots/" => "home#filter_ots", :as => :filter_ots

  match "marcado_documento/perform_work/:task_id/(:event)" => "marcado_documento#perform_work", :as => :marcado_documento_perform_work
  match "marcado_documento/realizar_marcaje_automatico" => "marcado_documento#realizar_marcaje_automatico", :as => :realizar_marcaje_automatico, :method => :post
  match "marcado_documento/save_xml_document" => "marcado_documento#save_xml_document", :as => :marcado_documento_save_xml_document, :method => :post
  match "marcado_documento/requiere_marcaje_automatico_event/:task_id" => "marcado_documento#requiere_marcaje_automatico_event", :as => :requiere_marcaje_automatico_event
  match "marcado_documento/no_requiere_marcaje_automatico_event/:task_id" => "marcado_documento#no_requiere_marcaje_automatico_event", :as => :no_requiere_marcaje_automatico_event
  match "marcado_documento/requiere_modificaciones_event/:task_id" => "marcado_documento#requiere_modificaciones_event", :as => :requiere_modificaciones_event
  match "marcado_documento/no_requiere_modificaciones_event/:task_id" => "marcado_documento#no_requiere_modificaciones_event", :as => :no_requiere_modificaciones_event
  match "marcado_documento/termina_correcciones_event/:task_id" => "marcado_documento#termina_correcciones_event", :as => :termina_correcciones_event
  match "marcado_documento/verifica_correcciones_event/:task_id" => "marcado_documento#verifica_correcciones_event", :as => :verifica_correcciones_event
  match "marcado_documento/termina_marcaje_automatico_event/:task_id" => "marcado_documento#termina_marcaje_automatico_event", :as => :termina_marcaje_automatico_event

  match "qa_documento/perform_work/:task_id/(:event)" => "qa_documento#perform_work", :as => :qa_documento_perform_work
  match "qa_documento/save_xml_document" => "qa_documento#save_xml_document", :as => :qa_documento_save_xml_document, :method => :post
  match "qa_documento/recibe_notificacion_event/:task_id" => "qa_documento#recibe_notificacion_event", :as => :recibe_notificacion_event
  match "qa_documento/comienza_validar_event/:task_id" => "qa_documento#comienza_validar_event", :as => :comienza_validar_event
  match "qa_documento/rechaza_event/:task_id" => "qa_documento#rechaza_event", :as => :rechaza_event
  match "qa_documento/aprueba_tarea_event/:task_id" => "qa_documento#aprueba_tarea_event", :as => :aprueba_tarea_event
  match "qa_documento/aprueba_ot_event/:task_id" => "qa_documento#aprueba_ot_event", :as => :aprueba_ot_event
  match "qa_documento/publica_documento_event/:task_id" => "qa_documento#publica_documento_event", :as => :publica_documento_event

  match "plan_cuenta/perform_work/:task_id/(:event)" => "plan_cuenta#perform_work", :as => :plan_cuenta_perform_work
  match "plan_cuenta/eligiendo_documento" => "plan_cuenta#eligiendo_documento"
  match "plan_cuenta/create_document" => "plan_cuenta#create_document", :as => :plan_cuenta_crear_documento, :method => :post
  match "plan_cuenta/create_asignar_tareas" => "plan_cuenta#create_asignar_tareas", :as => :crear_asignar_tareas, :method => :post
  match "plan_cuenta/create_notificar_analista" => "plan_cuenta#create_notificar_analista", :as => :crear_notificar_analista, :method => :post

  match "plan_diario/perform_work/:task_id/(:event)"=> "plan_diario#perform_work", :as => :plan_diario_perform_work
  match "plan_diario/eligiendo_documento" => "plan_diario#eligiendo_documento"
  match "plan_diario/en_marcaje_automatico" => "plan_diario#en_marcaje_automatico"
  match "plan_diario/evaluando_resultados" => "plan_diario#evaluando_resultados"
  match "plan_diario/planifica_asignar_tareas" => "plan_diario#planifica_asignar_tareas"
  match "plan_diario/asignando_tareas" => "plan_diario#asignando_tareas"
  match "plan_diario/notificar_equipos" => "plan_diario#notificar_equipos"
  match "plan_diario/create_document" => "plan_cuenta#create_document", :as => :plan_diario_crear_documento, :method => :post
  match "plan_diario/realizar_marcaje_automatico" => "plan_diario#realizar_marcaje_automatico", :as => :marcaje_automatico_plan_diario, :method => :post
  match "plan_diario/create_dividir_tareas" => "plan_diario#create_dividir_tareas", :as => :create_dividir_tareas, :method => :post

app/models/ot_type.rb
class OtType < ActiveRecord::Base
  has_many :ot

  OT_TYPE_CUENTA_INPUT    =  1
  OT_TYPE_SUMMARY_INPUT   =  2
  OT_TYPE_DS_INPUT        =  3
  OT_TYPE_CORRECTION      =  4
  OT_TYPE_HOSTORICAL_DS   =  5
  OT_TYPE_TP_ON_DEMAND    =  7
  OT_TYPE_BITACORA_UPDATE =  8
  OT_TYPE_INTEGRATION     =  9
  OT_TYPE_ANTICIPATED_DS  = 10
  OT_TYPE_PARTIAL_DS      = 11
end

app/controllers/ots_controller.rb
class OtsController < ApplicationController
  before_filter :set_menu_section

  def set_menu_section
    @accordion_section = 3
  end

  # GET /ots
  # GET /ots.json
  def index
    screen_name("Admin-Indice-OTs")
    @ots = Ot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ots }
    end
  end

  # GET /ots/1
  # GET /ots/1.json
  def show
    screen_name("Admin-Mostrar-OT")
    @ot = Ot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ot }
    end
  end

  # GET /ots/new
  # GET /ots/new.json
  def new
    screen_name("Admin-Nueva-OT")
    @ot = Ot.new
    @ot.created_by = current_user.id
    @ot.target_date = DateTime.now + 2

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ot }
    end
  end

  # GET /ots/1/edit
  def edit
    screen_name("Admin-Editar-OT")
    @ot = Ot.find(params[:id])
  end

  # POST /ots
  # POST /ots.json
  def create
    @ot = Ot.new(params[:ot])

    respond_to do |format|
      if @ot.save
        @ot.create_tasks(current_user)
        format.html { redirect_to @ot, notice: 'Ot was successfully created.' }
        format.json { render json: @ot, status: :created, location: @ot }
      else
        format.html { render action: "new" }
        format.json { render json: @ot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ots/1
  # PUT /ots/1.json
  def update
    @ot = Ot.find(params[:id])

    respond_to do |format|
      if @ot.update_attributes(params[:ot])
        format.html { redirect_to @ot, notice: 'Ot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ots/1
  # DELETE /ots/1.json
  def destroy
    @ot = Ot.find(params[:id])
    @ot.destroy

    respond_to do |format|
      format.html { redirect_to ots_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ots_helper.rb
module OtsHelper
end

app/views/ots/_form.html.erb
<%= form_for(@ot) do |f| %>
	<% if @ot.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@ot.errors.count, "error") %> prohibited this ot from being saved:</h2>
			<ul>
				<% @ot.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
	    <%= f.label(:ot_type_id, 'Tipo') %><br />
	    <%= collection_select(:ot, :ot_type_id, OtType.order("name ASC"), :id, :name) %>
	</div>

	<div class="field">
	    <%= f.label(:priority_id, 'Prioridad') %><br />
	    <%= collection_select(:ot, :priority_id, Priority.all, :id, :name) %>
	</div>

	<div class="field invisible">
	    <%= f.label(:created_by, 'Creada por') %><br />
	    <%= collection_select(:ot, :created_by, User.all, :id, :email) %>
	</div>

	<div class="field">
	    <%= f.label(:by_request_of, 'A pedido de') %><br />
	    <%= f.text_field(:by_request_of) %>
	</div>

	<div class="field">
		<%= f.label :target_date, "Fecha de entrega" %><br />
		<%= f.datetime_select :target_date %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/ots/edit.html.erb
<h1>Editing ot</h1>

<%= render 'form' %>

<%= link_to 'Show', @ot %> |
<%= link_to 'Back', ots_path %>

app/views/ots/index.html.erb
<h1>Ordenes de Trabajo</h1>

<table>
	<thead>
		<tr>
			<th>Tipo</th>
			<th>Prioridad</th>
			<th>Creada por</th>
			<th>Creada el</th>
			<th>Completada el</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<% @ots.each do |ot| %>
		<tr>
			<td><%= ot.ot_type.name %></td>
			<td><%= ot.priority.name %></td>
			<td><%= ot.owner.user_name %></td>
			<td><%= ot.created_on %></td>
			<td><%= ot.completed_on %></td>
			<td><%= link_to 'Show', ot %></td>
			<td><%= link_to 'Edit', edit_ot_path(ot) %></td>
			<td><%= link_to 'Destroy', ot, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<br />

<%= link_to 'New Ot', new_ot_path %>

app/views/ots/new.html.erb
<h1>Nueva OT</h1>

<%= render 'form' %>

<%= link_to 'Back', ots_path %>

app/views/ots/show.html.erb
<table>
	<tr>
		<th>Número de serie:</th>
		<td><%= @ot.serial_number %></td>
	</tr>
	<tr>
		<th>Prioridad:</th>
		<td><%= @ot.priority.name %></td>
	</tr>
	<tr>
		<th>Tipo:</th>
		<td><%= @ot.ot_type.name %></td>
	</tr>
	<tr>
		<th>A pedido de:</th>
		<td><%= @ot.by_request_of %></td>
	</tr>
	<tr>
		<th>Generada por/Agrupada en:</th>
		<td><%= @ot.parent_ot.name if !@ot.parent_ot.nil? %></td>
	</tr>
	<tr>
		<th>Documento fuente:</th>
		<td><%= @ot.source_frbr_manifestation.name if !@ot.source_frbr_manifestation.nil? %></td>
	</tr>
	<tr>
		<th>Documento marcado:</th>
		<td><%= @ot.target_frbr_manifestation.name if !@ot.target_frbr_manifestation.nil? %></td>
	</tr>
	<tr>
		<th>Creada por:</th>
		<td><%= @ot.owner.user_name %></td>
	</tr>
	<tr>
		<th>Creada el:</th>
		<td><%= @ot.created_on %></td>
	</tr>
	<tr>
		<th>Fecha de entrega:</th>
		<td><%= @ot.target_date %></td>
	</tr>
	<tr>
		<th>Completada el:</th>
		<td><%= @ot.completed_on %></td>
	</tr>
	<tr>
		<th>Tarea actual:</th>
		<td><%= @ot.current_task.name %></td>
	</tr>
	<tr>
		<th>Actividad actual:</th>
		<td><%= @ot.current_step %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_ot_path(@ot) %> |
<%= link_to 'Back', ots_path %>