config/routes.rb
Bcn::Application.routes.draw do  
  match "trabajo_parlamentario/index" => "trabajo_parlamentario#index", :as => :trabajo_parlamentario
  match "trabajo_parlamentario/create" => "trabajo_parlamentario#create", :via => :post, :as => :create_trabajo_parlamentario

  resources :bitacoras
  resources :tramite_normativos
  resources :tramite_constitucionals
  resources :debate_types
  resources :tp_generated_params
  resources :taxonomy_terms
  resources :taxonomy_categories
  resources :tp_parameters
  resources :default_users_by_ot_types
  resources :am_module_configurations
  resources :poblamiento_generated_params
  resources :poblamiento_import_locations
  resources :poblamiento_file_formats
  resources :doc_type_am_configurations
  resources :task_transitions
  resources :poblamiento_params
  resources :observation_types
  resources :target_document_versions
  resources :markup_tools
  resources :am_configurations
  resources :am_observations
  resources :am_run_observation_types
  resources :am_results
  resources :intermediaries
  resources :delivery_methods
  resources :observations
  resources :ot_states
  resources :audits
  resources :frbr_manifestations
  resources :frbr_expressions
  resources :frbr_document_types
  resources :frbr_works
  resources :frbr_bcn_types
  resources :frbr_entities
  resources :task_types
  resources :roles
  resources :priorities
  resources :ot_types
  resources :ots
  resources :tasks
  devise_for :users

  match "parlamentarians" => 'parlamentarians#create', :via => :post
  match "parlamentarians" => 'parlamentarians#index', :as => :parlamentarians
  match "parlamentarians/new" => 'parlamentarians#new', :as => :new_parlamentarian
  match "parlamentarians/:rdf_uri" => 'parlamentarians#update', :as => :update_parlamentarian, :via => :put
  match "parlamentarians/:rdf_uri" => 'parlamentarians#destroy', :as => :destroy_parlamentarian, :via => :delete
  match "parlamentarians/:rdf_uri" => 'parlamentarians#show', :as => :parlamentarian
  match "parlamentarians/:rdf_uri/edit" => 'parlamentarians#edit', :as => :edit_parlamentarian

  match "rdf_interventions" => 'rdf_interventions#create', :via => :post
  match "rdf_interventions" => 'rdf_interventions#index', :as => :rdf_interventions
  match "rdf_interventions/new" => 'rdf_interventions#new', :as => :new_rdf_intervention
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#update', :as => :update_rdf_intervention, :via => :put
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#destroy', :as => :destroy_rdf_intervention, :via => :delete
  match "rdf_interventions/:rdf_uri" => 'rdf_interventions#show', :as => :rdf_intervention
  match "rdf_interventions/:rdf_uri/edit" => 'rdf_interventions#edit', :as => :edit_rdf_intervention

  match "parties" => 'parties#create', :via => :post
  match "parties" => 'parties#index', :as => :rdf_parties
  match "parties/new" => 'parties#new', :as => :new_rdf_party
  match "parties/:rdf_uri" => 'parties#update', :as => :update_rdf_party, :via => :put
  match "parties/:rdf_uri" => 'parties#destroy', :as => :destroy_rdf_party, :via => :delete
  match "parties/:rdf_uri" => 'parties#show', :as => :rdf_party
  match "parties/:rdf_uri/edit" => 'parties#edit', :as => :edit_rdf_party

  match "qualities" => 'qualities#create', :via => :post
  match "qualities" => 'qualities#index', :as => :rdf_qualities
  match "qualities/new" => 'qualities#new', :as => :new_rdf_quality
  match "qualities/:rdf_uri" => 'qualities#update', :as => :update_rdf_quality, :via => :put
  match "qualities/:rdf_uri" => 'qualities#destroy', :as => :destroy_rdf_quality, :via => :delete
  match "qualities/:rdf_uri" => 'qualities#show', :as => :rdf_quality
  match "qualities/:rdf_uri/edit" => 'qualities#edit', :as => :edit_rdf_quality

  match "participation_types" => 'participation_types#create', :via => :post
  match "participation_types" => 'participation_types#index', :as => :rdf_participation_types
  match "participation_types/new" => 'participation_types#new', :as => :new_rdf_participation_type
  match "participation_types/:rdf_uri" => 'participation_types#update', :as => :update_rdf_participation_type, :via => :put
  match "participation_types/:rdf_uri" => 'participation_types#destroy', :as => :destroy_rdf_participation_type, :via => :delete
  match "participation_types/:rdf_uri" => 'participation_types#show', :as => :rdf_participation_type
  match "participation_types/:rdf_uri/edit" => 'participation_types#edit', :as => :edit_rdf_participation_type

  get "home/index"
  match "home/show_empty" => "home#show_empty", :as => :mostrar_vacio
  match "home/show_admin" => "home#show_admin", :as => :mostrar_admin
  match "home/show_analist" => "home#show_analist", :as => :mostrar_analista
  match "home/show_qa_analist" => "home#show_qa_analist", :as => :mostrar_analista_qa
  match "home/show_planner" => "home#show_planner", :as => :mostrar_planificador
  match "home/show_ot/:ot_id" => "home#show_ot", :as => :mostrar_ot
  match "home/edit_ot/:ot_id" => "home#edit_ot", :as => :editar_ot
  match "home/update_ot" => "home#update_ot", :as => :actualizar_ot, :method => :post
  match "home/show_document/:frbr_manifestation_id" => "home#show_document", :as => :mostrar_documento
  match "home/show_am_result/:am_result_id" => "home#show_am_result", :as => :mostrar_resultado_ma
  match "home/create_observation" => "home#create_observation", :as => :create_observation, :method => :post
  match "home/new_ot" => "home#new_ot", :as => :home_new_ot
  match "home/create_new_ot" => "home#create_new_ot", :as => :create_new_ot, :method => :post
  match "home/clear_database" => "home#clear_database", :as => :clear_database

  match "home/filter_ots/" => "home#filter_ots", :as => :filter_ots

  match "marcado_documento/perform_work/:task_id/(:event)" => "marcado_documento#perform_work", :as => :marcado_documento_perform_work
  match "marcado_documento/realizar_marcaje_automatico" => "marcado_documento#realizar_marcaje_automatico", :as => :realizar_marcaje_automatico, :method => :post
  match "marcado_documento/save_xml_document" => "marcado_documento#save_xml_document", :as => :marcado_documento_save_xml_document, :method => :post
  match "marcado_documento/requiere_marcaje_automatico_event/:task_id" => "marcado_documento#requiere_marcaje_automatico_event", :as => :requiere_marcaje_automatico_event
  match "marcado_documento/no_requiere_marcaje_automatico_event/:task_id" => "marcado_documento#no_requiere_marcaje_automatico_event", :as => :no_requiere_marcaje_automatico_event
  match "marcado_documento/requiere_modificaciones_event/:task_id" => "marcado_documento#requiere_modificaciones_event", :as => :requiere_modificaciones_event
  match "marcado_documento/no_requiere_modificaciones_event/:task_id" => "marcado_documento#no_requiere_modificaciones_event", :as => :no_requiere_modificaciones_event
  match "marcado_documento/termina_correcciones_event/:task_id" => "marcado_documento#termina_correcciones_event", :as => :termina_correcciones_event
  match "marcado_documento/verifica_correcciones_event/:task_id" => "marcado_documento#verifica_correcciones_event", :as => :verifica_correcciones_event
  match "marcado_documento/termina_marcaje_automatico_event/:task_id" => "marcado_documento#termina_marcaje_automatico_event", :as => :termina_marcaje_automatico_event

  match "qa_documento/perform_work/:task_id/(:event)" => "qa_documento#perform_work", :as => :qa_documento_perform_work
  match "qa_documento/save_xml_document" => "qa_documento#save_xml_document", :as => :qa_documento_save_xml_document, :method => :post
  match "qa_documento/recibe_notificacion_event/:task_id" => "qa_documento#recibe_notificacion_event", :as => :recibe_notificacion_event
  match "qa_documento/comienza_validar_event/:task_id" => "qa_documento#comienza_validar_event", :as => :comienza_validar_event
  match "qa_documento/rechaza_event/:task_id" => "qa_documento#rechaza_event", :as => :rechaza_event
  match "qa_documento/aprueba_tarea_event/:task_id" => "qa_documento#aprueba_tarea_event", :as => :aprueba_tarea_event
  match "qa_documento/aprueba_ot_event/:task_id" => "qa_documento#aprueba_ot_event", :as => :aprueba_ot_event
  match "qa_documento/publica_documento_event/:task_id" => "qa_documento#publica_documento_event", :as => :publica_documento_event

  match "plan_cuenta/perform_work/:task_id/(:event)" => "plan_cuenta#perform_work", :as => :plan_cuenta_perform_work
  match "plan_cuenta/eligiendo_documento" => "plan_cuenta#eligiendo_documento"
  match "plan_cuenta/create_document" => "plan_cuenta#create_document", :as => :plan_cuenta_crear_documento, :method => :post
  match "plan_cuenta/create_asignar_tareas" => "plan_cuenta#create_asignar_tareas", :as => :crear_asignar_tareas, :method => :post
  match "plan_cuenta/create_notificar_analista" => "plan_cuenta#create_notificar_analista", :as => :crear_notificar_analista, :method => :post

  match "plan_diario/perform_work/:task_id/(:event)"=> "plan_diario#perform_work", :as => :plan_diario_perform_work
  match "plan_diario/eligiendo_documento" => "plan_diario#eligiendo_documento"
  match "plan_diario/en_marcaje_automatico" => "plan_diario#en_marcaje_automatico"
  match "plan_diario/evaluando_resultados" => "plan_diario#evaluando_resultados"
  match "plan_diario/planifica_asignar_tareas" => "plan_diario#planifica_asignar_tareas"
  match "plan_diario/asignando_tareas" => "plan_diario#asignando_tareas"
  match "plan_diario/notificar_equipos" => "plan_diario#notificar_equipos"
  match "plan_diario/create_document" => "plan_cuenta#create_document", :as => :plan_diario_crear_documento, :method => :post
  match "plan_diario/realizar_marcaje_automatico" => "plan_diario#realizar_marcaje_automatico", :as => :marcaje_automatico_plan_diario, :method => :post
  match "plan_diario/create_dividir_tareas" => "plan_diario#create_dividir_tareas", :as => :create_dividir_tareas, :method => :post

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
  belongs_to :tramite_constitucional
  belongs_to :tramite_normativo
  belongs_to :user
end

app/controllers/bitacoras_controller.rb
class BitacorasController < ApplicationController
  before_filter :set_menu_section

  def set_menu_section
    @accordion_section = 7
  end

  # GET /bitacoras
  # GET /bitacoras.json
  def index
    @bitacoras = Bitacora.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bitacoras }
    end
  end

  # GET /bitacoras/1
  # GET /bitacoras/1.json
  def show
    @bitacora = Bitacora.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bitacora }
    end
  end

  # GET /bitacoras/new
  # GET /bitacoras/new.json
  def new
    @bitacora = Bitacora.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bitacora }
    end
  end

  # GET /bitacoras/1/edit
  def edit
    @bitacora = Bitacora.find(params[:id])
  end

  # POST /bitacoras
  # POST /bitacoras.json
  def create
    @bitacora = Bitacora.new(params[:bitacora])

    respond_to do |format|
      if @bitacora.save
        format.html { redirect_to @bitacora, notice: 'Bitacora was successfully created.' }
        format.json { render json: @bitacora, status: :created, location: @bitacora }
      else
        format.html { render action: "new" }
        format.json { render json: @bitacora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bitacoras/1
  # PUT /bitacoras/1.json
  def update
    @bitacora = Bitacora.find(params[:id])

    respond_to do |format|
      if @bitacora.update_attributes(params[:bitacora])
        format.html { redirect_to @bitacora, notice: 'Bitacora was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bitacora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bitacoras/1
  # DELETE /bitacoras/1.json
  def destroy
    @bitacora = Bitacora.find(params[:id])
    @bitacora.destroy

    respond_to do |format|
      format.html { redirect_to bitacoras_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/views/bitacoras/_form.html.erb
<%= form_for(@bitacora) do |f| %>
	<% if @bitacora.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@bitacora.errors.count, "error") %> prohibited this bitacora from being saved:</h2>
			<ul>
				<% @bitacora.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :bulletin_id, "Boletín" %><br />
		<%= f.number_field :bulletin_id %>
	</div>

	<div class="field">
		<%= f.label :frbr_manifestation_id, "Documento" %><br />
		<%= f.number_field :frbr_manifestation_id %>
	</div>

	<div class="field">
		<%= f.label :tramite_constitucional_id, "Trámite Constitucional" %><br />
		<%= f.select :tramite_constitucional_id, TramiteConstitucional.all.map { |tn| [tn.name, tn.id] }, :selected => @bitacora.tramite_constitucional_id %>
	</div>

	<div class="field">
		<%= f.label :tramite_normativo_id, "Trámite Normativo" %><br />
		<%= f.select :tramite_normativo_id, TramiteNormativo.all.map { |tn| [tn.name, tn.id] }, :selected => @bitacora.tramite_normativo_id %>
	</div>

	<div class="field">
		<%= f.label :comments, "Comentarios" %><br />
		<%= f.text_area :comments %>
	</div>

	<div class="field">
		<%= f.label :user_id, "Usuario" %><br />
		<%= f.select :user_id, User.all.map { |tn| [tn.user_name, tn.id] }, :selected => @bitacora.user_id %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/bitacoras/edit.html.erb
<h1>Editing bitacora</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitacora %> |
<%= link_to 'Back', bitacoras_path %>

app/views/bitacoras/index.html.erb
<h1>Bitácora</h1>

<table>
	<thead>
		<tr>
			<th>Boletín</th>
			<th>Documento</th>
			<th>Trámite constitucional</th>
			<th>Trámite normativo</th>
			<th>Comentarios</th>
			<th>Usuario</th>
			<th>Fecha</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @bitacoras.each do |bitacora| %>
		<tr>
			<td><%= bitacora.bulletin_id %></td>
			<td><%= bitacora.frbr_manifestation_id %></td>
			<td><%= bitacora.tramite_constitucional.name %></td>
			<td><%= bitacora.tramite_normativo.name %></td>
			<td><%= bitacora.comments %></td>
			<td><%= bitacora.user.user_name %></td>
			<td><%= bitacora.updated_at %></td>
			<td><%= link_to 'Show', bitacora %></td>
			<td><%= link_to 'Edit', edit_bitacora_path(bitacora) %></td>
			<td><%= link_to 'Destroy', bitacora, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br />

<%= link_to 'New Bitacora', new_bitacora_path %>

app/views/bitacoras/new.html.erb
<h1>New bitacora</h1>

<%= render 'form' %>

<%= link_to 'Back', bitacoras_path %>

app/views/bitacoras/show.html.erb
<p>
  <b>Bulletin:</b>
  <%= @bitacora.bulletin_id %>
</p>

<p>
  <b>Frbr manifestation:</b>
  <%= @bitacora.frbr_manifestation_id %>
</p>

<p>
  <b>Tramite constitucional:</b>
  <%= @bitacora.tramite_constitucional_id %>
</p>

<p>
  <b>Tramite normativo:</b>
  <%= @bitacora.tramite_normativo_id %>
</p>

<p>
  <b>Comments:</b>
  <%= @bitacora.comments %>
</p>

<p>
  <b>User:</b>
  <%= @bitacora.user_id %>
</p>


<%= link_to 'Edit', edit_bitacora_path(@bitacora) %> |
<%= link_to 'Back', bitacoras_path %>